- id: blackt
  name: blackt
  description: "Blackt: The uncompromising Python code formatter"
  entry: blackt
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
