repos:
  - repo: https://github.com/FHPythonUtils/Blackt
    rev: '2021'
    hooks:
      - id: blackt

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
      - id: pylint
        args: [--disable=import-error,--jobs=0, --fail-under=9.8, --ignore-patterns=test.*?py]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: "tests/data/"
      - id: end-of-file-fixer
        exclude: "tests/data/"

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/boidolr/pre-commit-images
    rev: v1.0.0
    hooks:
      - id: optimize-avif
        exclude: "tests/data/"
      - id: optimize-jpg
        exclude: "tests/data/"
      - id: optimize-png
        exclude: "tests/data/"
      - id: optimize-svg
        exclude: "tests/data/"
      - id: optimize-webp
        exclude: "tests/data/"
